
[[Snippets]]
  Description = "shell's nil"
  Output = ""
  Tag = []
  command = ": ;"

[[Snippets]]
  Description = "echo"
  Output = ""
  Tag = []
  command = "echo"

[[Snippets]]
  Description = "Initialize MacBook Pro connection into TechPort"
  Output = ""
  Tag = []
  command = "lsif\nlsip\npull-vast.id_rsa 0\nvastconnect 192.168.2.2\nauto-copy-ssh-id 192.168.2.2"
